load("//:tools.bzl", "manta_binary")


manta_binary(src="CminusParserDriver.cpp")
manta_binary(src="CodegenDriver.cpp")
manta_binary(src="DescriptionParserDriver.cpp")
manta_binary(src="GeneratedParserDriver.cpp")
manta_binary(src="ProgramaticParserDriver.cpp")