
cc_library(
    name="utility", 
    srcs=glob(["*.cpp"]),
    hdrs=glob(["*.h"]),
    copts = ["-std=c++20"],
    visibility=["//visibility:public"],
    deps=[
        "@lightning//include:lightning",
    ],
    
)