//
// Created by Nathaniel Rupprecht on 7/30/23.
//

#ifndef MANTA_INCLUDE_MANTA_UTILITY_STREAMFUNCTIONS_H_
#define MANTA_INCLUDE_MANTA_UTILITY_STREAMFUNCTIONS_H_

#endif //MANTA_INCLUDE_MANTA_UTILITY_STREAMFUNCTIONS_H_
